
--
-- Name: banco; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.banco (
    id bigint NOT NULL,
    nome_do_banco character varying(255),
    numero_do_banco integer NOT NULL
);


--
-- Name: banco_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.banco ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.banco_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cliente; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cliente (
    id bigint NOT NULL,
    cpf character varying(255),
    endereco character varying(255),
    email character varying(255),
    nome character varying(255),
    telefone character varying(255)
);


--
-- Name: cliente_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cliente ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cliente_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: conta_corrente; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.conta_corrente (
    id bigint NOT NULL,
    agencia character varying(255),
    conta character varying(255),
    data_usuario timestamp without time zone,
    saldo numeric(19,2),
    cliente_id bigint,
    banco_id bigint
);


--
-- Name: conta_corrente_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.conta_corrente ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.conta_corrente_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: status_pagamento; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.status_pagamento (
    momento timestamp without time zone,
    transacao_id bigint NOT NULL
);


--
-- Name: transacao; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.transacao (
    id bigint NOT NULL,
    data_transacao timestamp without time zone,
    tipo_transacao integer,
    valor numeric(19,2),
    conta_destino_id bigint,
    conta_origem_id bigint
);


--
-- Name: transacao_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.transacao ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transacao_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: banco banco_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.banco
    ADD CONSTRAINT banco_pkey PRIMARY KEY (id);


--
-- Name: cliente cliente_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT cliente_pkey PRIMARY KEY (id);


--
-- Name: conta_corrente conta_corrente_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conta_corrente
    ADD CONSTRAINT conta_corrente_pkey PRIMARY KEY (id);


--
-- Name: status_pagamento status_pagamento_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.status_pagamento
    ADD CONSTRAINT status_pagamento_pkey PRIMARY KEY (transacao_id);


--
-- Name: transacao transacao_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transacao
    ADD CONSTRAINT transacao_pkey PRIMARY KEY (id);


--
-- Name: transacao fk560qx970s8okw1phphgfaqwrj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transacao
    ADD CONSTRAINT fk560qx970s8okw1phphgfaqwrj FOREIGN KEY (conta_destino_id) REFERENCES public.conta_corrente(id);


--
-- Name: conta_corrente fkalpvef57mclky5ox1feos51s8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conta_corrente
    ADD CONSTRAINT fkalpvef57mclky5ox1feos51s8 FOREIGN KEY (cliente_id) REFERENCES public.cliente(id);


--
-- Name: conta_corrente fkill7xsvkyf3e6t80m35cbh89h; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conta_corrente
    ADD CONSTRAINT fkill7xsvkyf3e6t80m35cbh89h FOREIGN KEY (banco_id) REFERENCES public.banco(id);


--
-- Name: transacao fkr7l9siftqxtwgls6xurdritd0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transacao
    ADD CONSTRAINT fkr7l9siftqxtwgls6xurdritd0 FOREIGN KEY (conta_origem_id) REFERENCES public.conta_corrente(id);


--
-- Name: status_pagamento fkr9xofjwv2q1twu6rsnlb8j5cy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.status_pagamento
    ADD CONSTRAINT fkr9xofjwv2q1twu6rsnlb8j5cy FOREIGN KEY (transacao_id) REFERENCES public.transacao(id);


--
-- PostgreSQL database dump complete
--

